# Generated by Django 3.1 on 2020-08-13 17:01

import billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillerServicesUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_license', models.ImageField(blank=True, null=True, upload_to=billing.models.upload_path)),
                ('file_signatories', models.ImageField(blank=True, null=True, upload_to=billing.models.upload_path)),
                ('file_collection', models.ImageField(blank=True, null=True, upload_to=billing.models.upload_path)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
