# Generated by Django 3.1 on 2020-08-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20200813_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billerservicesuploads',
            name='file_collection',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='billerservicesuploads',
            name='file_license',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='billerservicesuploads',
            name='file_signatories',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
